# Generated by Django 4.1.3 on 2022-12-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='queued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.TextField(default='12/31/2050'),
        ),
    ]
